name: Flywheel SSH Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Flywheel
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.SSH_USER }}
        TARGET: wp-content/themes/bull-dawgs/
