name: Flywheel SSH Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: ${{ secrets.SSH_USER }}
        TARGET: /www/wp-content/themes/
